### ISSUE TITLE
CanvasRenderingContext2D is not defined

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#126]
Hi filerobot-image-editor, Thank you for making it so I can use it. In the process of using, I have encountered a problem, hope you can support to fix it

When I test wit jest, it gives the following error:

● Test suite failed to run

    ReferenceError: CanvasRenderingContext2D is not defined

      1 | import React from 'react'
      2 | import PropTypes from 'prop-types'
    > 3 | import FilerobotImageEditor from 'filerobot-image-editor'
        | ^

      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/utils/canvas-round.js:8:1)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/components/Preview/ImageManipulator.js:22:1)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/components/Preview/Preview.js:14:48)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/components/index.js:45:39)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/ImageEditor.js:14:15)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/ImageEditorWrapper.js:10:43)
      at Object.<anonymous> (node_modules/filerobot-image-editor/dist/index.js:13:50)

I look forward to hearing from you. Thanks very much!

**Comment by tiendd-tmh** [comment]
@AhmeeedMostafa Thanks for your answer. I have fixed it. Thank you very much!
