### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kandarppatel** [scaleflex/filerobot-image-editor#54]
We are trying to use this module with our React SSR (Server Side Rendering) project and its keep giving us below error.

```
ReferenceError: window is not defined
at Object.<anonymous> (/var/www/app/node_modules/filerobot-image-editor/dist/lib/caman/core/index.js:990:1)
at Module._compile (internal/modules/cjs/loader.js:778:30)\
at Module._compile (/var/www/app/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Object.newLoader [as .js] (/var/www/app/node_modules/pirates/lib/index.js:104:7)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
```

We have tried different solutions suggested online by setting window as global or conditioning in componentDidMount life cycle method but non of them working. 

Is there any work around for this ?

**Comment by dzmitry-stramavus** [comment]
hey @kandarppatel ,

We put SSR support for the next release. (ETA ~1 week)

**Comment by kandarppatel** [comment]
Thank you @dzmitry-stramavus. Thanks for an amazing module.

**Comment by dzmitry-stramavus** [comment]
hey @kandarppatel ,

done in **3.9.2**, can you please test if it works for?

**Comment by kandarppatel** [comment]
Thank you for the update but now getting below error.
```
ReferenceError: CanvasRenderingContext2D is not defined at Object.
<anonymous> (/var/www/app/node_modules/filerobot-image-editor/dist/utils/canvas-round-rect.js:8:16)
```

**Comment by AhmeeedMostafa** [comment]
@kandarppatel closing this issue since it's solved, please let us know if you still facing such a problem.

**Comment by johnsutor** [comment]
If anyone encounters any issues with this, you can simply do 

```js
import dynamic from "next/dynamic";
const FilerobotImageEditor = dynamic(() => import("react-filerobot-image-editor"), {
  ssr: false,
});
```

in Next.js
